# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NHIAPDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'NHHUDExtend'
pod 'NHIAP', :path => '../NHIAP.podspec'


  # Pods for NHIAPDemo

  target 'NHIAPDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NHIAPDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
